Updated fetch import to fix server error
ava-labs/avalanchejs pull request #626
Opened 2022-07-14 21:46 UTC by Mukul-code-rep

I was working with avalanchejs and tried to automate my code using rest api created from express and morgan. When I tried to run it using heroku, it gave reference errors and upon further research, I found a fix and think that it should be put on the package.

2022-07-15 17:09 UTC, barbas-gen commented
Running into same issue

2022-07-15 18:04 UTC, LoganDiliberto-Crypto commented
Same issue here and this seemed to work

2022-08-24 13:49 UTC, gergelylovas requested changes
These changes are not the way to make avalancheJS work with Node<18.

This only works because of the import of `node-fetch` which polyfills the missing `fetch` API and not because of the changes of `Request` => `f.Request` and `Headers` => `f.Headers`

The import of `node-fetch` and thus polyfilling the `fetch` API should happen in the consumer project, prior the avalancheJS imports. Which will make AvalancheJS work in Node <18 runtimes.

2022-08-24 13:49 UTC, gergelylovas commented on src/utils/fetchadapter.ts
> +const f = require('node-fetch');
`node-fetch` is not amongst the dependencies of avalancheJS.

2022-08-24 14:03 UTC, closed without merging